name: Create Release

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  create-release:
    runs-on: ubuntu-latest

    env:
      TAG_NAME: "v1.0.$(git rev-list --count HEAD)"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Tag
        run: |
          git tag $TAG_NAME -m "Version $TAG_NAME"
          git push origin $TAG_NAME --quiet --set-upstream

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          body: |
            Release ${{ env.TAG_NAME }}

            Add release notes here.
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
