on:
  workflow_dispatch:
    branches:
      - master
      - develop
      
    inputs:
      in_tag:
        description: 'release version'
        required: true
        default: '1.0'
      
      enviro:
        description: 'release enviroment'
        required: true
        default: '1.0'

name: Create-Release

jobs:
  build:
    name: Create-Release
    runs-on: ubuntu-latest
    steps:
    
      - name: Create Not All Release
        if: ${{ github.event.inputs.enviro != 'ALL' }}
        id: create_notAll_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.enviro }}_v${{ github.event.inputs.in_tag }}
          release_name: ${{ github.event.inputs.enviro }}_v${{ github.event.inputs.in_tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Create Test Release
        if: ${{ github.event.inputs.enviro == 'ALL' }}
        id: create_test_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: test${{ github.event.inputs.in_tag }}
          release_name: test_v${{ github.event.inputs.in_tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Create Staging Release
        if: ${{ github.event.inputs.enviro == 'ALL' }}
        id: create_staging_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: staging_v${{ github.event.inputs.in_tag }}
          release_name: staging_v${{ github.event.inputs.in_tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
          
      - name: Create Production Release
        if: ${{ github.event.inputs.enviro == 'ALL' }}
        id: create_production_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: production_v${{ github.event.inputs.in_tag }}
          release_name: production_v${{ github.event.inputs.in_tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
