on:
  workflow_dispatch:
    branches:
      - master
      - develop
    inputs:
      enviro:
        type: choice
        description: environment
        options: 
          - test
          - staging
          - production

      in_tag:
        description: 'release tag'
        required: true
        default: '1.0'

name: Create Release2

jobs:
  build:
    name: Create Release2
    runs-on: ubuntu-latest
    steps:
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.enviro }}_v${{ github.event.inputs.in_tag }}
          release_name: ${{ github.event.inputs.enviro }}_v${{ github.event.inputs.in_tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
