name: "TheRealOne"

on:
  workflow_dispatch:
    branches:
      - master
      - develop
      - IdoGvili-patch-1
    inputs:
      enviro:
        type: choice
        description: enviroment
        options: 
        - test
        - staging
        - production

jobs:
     
  idoReleseas:
    name: idoReleseas
    runs-on: ubuntu-latest
   # strategy:
   #   matrix:
   #     service:
   #       - engage
   #       - engage-tenant
   #       - engage-admin
    

      # Default env vars
      
      - name: Assign default GitHub env variables
        run: |
          echo HELLOWWWWWWWWWW
          echo ${{ github.event.inputs.name }}
          echo "FINAL_INPUT = ${{ github.event.inputs.enviro }}" >> $GITHUB_ENV
          FINAL_INPUT="${{ github.event.inputs.enviro }}"
          echo "FINAL_INPUT = $FINAL_INPUT"

          if [[ $FINAL_INPUT == test_* ]]; then
            echo environment="test" >> $GITHUB_ENV
            echo distId="E333ZBF8OB0KGL" >> $GITHUB_ENV
            echo distUrl="https://d13imkh013nlqg.cloudfront.net" >> $GITHUB_ENV
      
          elif [[ $FINAL_INPUT == staging_* ]]; then
            echo environment="staging" >> $GITHUB_ENV
            echo distId="E3DIJQC07QF41Q" >> $GITHUB_ENV
            echo distUrl="https://d3tn5qru9slb7c.cloudfront.net" >> $GITHUB_ENV

          elif [[ $FINAL_INPUT == production_* ]]; then
            echo environment="production" >> $GITHUB_ENV
            echo distId="E6TVK39UORE10" >> $GITHUB_ENV
            echo distUrl="https://d34b54r33pmp3l.cloudfront.net" >> $GITHUB_ENV
  
          fi
          echo  $FINAL_INPUT
          echo  $GITHUB_ENV
