name: Release Workflow

on:
  workflow_dispatch:

jobs:
  get-latest-release-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get latest release tag and extract version
      id: get-version
      run: |
        TAG=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/releases/latest \
          | jq -r .tag_name)

        # Extract version using regular expression
        if [[ "$TAG" =~ (test|staging|production)_([0-9]+\.[0-9]+\.[0-9]+) ]]; then
          VERSION="${BASH_REMATCH[2]}"
        else
          echo "Failed to extract version from tag: $TAG"
          exit 1
        fi

        echo "Latest release version is $VERSION"
        echo "$VERSION"

    - name: Assign default GitHub env variables
        run: |
          echo HELLOWWWWWWWWWW
          echo ${{ github.event.inputs.name }}
          echo "FINAL_INPUT = ${in_tag}_${in_ver} ${{ github.event.inputs.name }}" >> $GITHUB_ENV
          FINAL_INPUT="$VERSION"
          echo "FINAL_INPUT = $FINAL_INPUT"
          if [[ $FINAL_INPUT == test_* ]]; then
            echo environment="test" >> $GITHUB_ENV
            echo distId="E333ZBF8OB0KGL" >> $GITHUB_ENV
            echo distUrl="https://d13imkh013nlqg.cloudfront.net" >> $GITHUB_ENV
      
          elif [[ $FINAL_INPUT == staging_* ]]; then
            echo environment="staging" >> $GITHUB_ENV
            echo distId="E3DIJQC07QF41Q" >> $GITHUB_ENV
            echo distUrl="https://d3tn5qru9slb7c.cloudfront.net" >> $GITHUB_ENV

          elif [[ $FINAL_INPUT == production_* ]]; then
            echo environment="production" >> $GITHUB_ENV
            echo distId="E6TVK39UORE10" >> $GITHUB_ENV
            echo distUrl="https://d34b54r33pmp3l.cloudfront.net" >> $GITHUB_ENV

          fi
          echo  $FINAL_INPUT
          echo  $GITHUB_ENV
