name: "new-Release"

on:
  workflow_dispatch:
    branches:
      - master
      - develop
    inputs:
      enviro:
        type: choice
        description: environment
        options: 
          - test
          - staging
          - production
          - ALL
      in_ver:
        description: 'release version'
        required: true
        default: '1.0'
    

jobs:
  release:
    name: new-Release

    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        enviroment:
          - test
          - staging
          - production

    steps:
      - name: "Determine tag"
        id: 'tag_id'
        run: |
         TAG=${{ github.event.inputs.enviro }}_v${{ github.event.inputs.in_ver }}
         echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub Release Not All
        if: ${{ github.event.inputs.enviro != 'ALL' }}
        run: |
          echo ${{ steps.tag_id.outputs.TAG }}
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/vi-technologies/frontend-vi-engage/releases \
          -d '{"tag_name":"${{ steps.tag_id.outputs.TAG }}","name":"${{ steps.tag_id.outputs.TAG }}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
    
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release All Three
        if: ${{ github.event.inputs.enviro == 'ALL' }}
        run: |
          echo ${{ steps.tag_id.outputs.TAG }}
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/vi-technologies/frontend-vi-engage/releases \
          -d '{"tag_name":"${{ matrix.enviroment }}_v${{github.event.inputs.in_ver }}","name":"${{ matrix.enviroment }}_v${{github.event.inputs.in_ver }}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
    
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
