name: "new-Release"

on:
  workflow_dispatch:
    branches:
      - master
      - develop
      - IdoGvili-patch-1
    inputs:
      enviro:
        description: 'release version'
        required: true
        default: '1.0'
      in_tag:
        description: 'release version'
        required: true
        default: '1.0'

jobs:
  release:
    name: new-Release

    runs-on: "ubuntu-latest"

    steps:
      - name: "Determine tag"
        id: 'tag_id'
        run: |
         TAG=${{ github.event.inputs.enviro }}_v${{ github.event.inputs.in_tag }}
         echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub Release
        run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/vi-technologies/frontend-vi-engage/releases \
            -d '{"tag_name":${{ steps.tag_id.outputs.TAG }},"target_commitish":"master","name":${{ steps.tag_id.outputs.TAG }},"body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up release data
        id: releaseData
        run: echo "::set-output name=releaseData::{\"tag_name\":\"v1.0.0\",\"name\":\"Release 1.0.0\",\"body\":\"Release notes for version 1.0.0\"}"